version: "3.9"
services:
  db:
    image: timescale/timescaledb:latest-pg14
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=onboardpi
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
  web:
    image: bgunson/onboardpi-web
    ports: 
      - "80:8080"
    volumes: 
      - /var/lib/onboardpi/data:/var/lib/onboardpi/data
    environment:
      - POSTGRES_HOST=db
      - SETTINGS_DIR=/var/lib/onboardpi/data
    depends_on:
      - db
  obd:
    image: bgunson/onboardpi-obd
    ports: 
      - "60000:60000"
    volumes:
      - /var/lib/onboardpi/data:/var/lib/onboardpi/data:ro
      - /dev:/dev
    # If you know your obd adapter's serial port will not change use device mapping and comment out '/dev:/dev' under volumes
    # devices: 
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      - SETTINGS_DIR=/var/lib/onboardpi/data
    depends_on:
      - web

volumes:
  db_data: