name: demo

on: 
  workflow_dispatch:
  push:
    paths:
      - 'web/client/**'
    tags:
      - 'v*'

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - 
      name: Install Node Modules (client)
      run: npm install
      working-directory: ./web/client
    - 
      name: Build Client
      run: npm run build-demo
      working-directory: ./web/client
    - 
      name: Publish to gh-pages
      run: npx angular-cli-ghpages --dir=../public --no-silent --name=${{ github.actor }} --email=${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com --repo=https://github.com/bgunson/onboardpi.git
      working-directory: ./web/client
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    