name: tests

on:
  push:
    paths:
      - 'obd/**'
      - 'web/**'

jobs: 
  test-obd:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - 
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./obd
      - 
        name: Test obd with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          python -m pytest 
        working-directory: ./obd
      - 
        name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - 
        name: Install web dependencies 
        run: npm install
        working-directory: ./web
      -
        name: Test OBD API
        run: |
          export SETTINGS_DIR=./obd/tests/test_configs
          python obd/server.py & 
          cd web
          npm run test-obd
  test-web:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - 
      name: Install client dependencies
      run: npm install
      working-directory: ./web/client
    - 
      name: Test client
      run: npm run test-ci
      working-directory: ./web/client
    -
      name: Install web server dependencies
      run: npm install
      working-directory: ./web
    - 
      name: Test web server
      run: npm test
      working-directory: ./web
