name: test pytest

on:
  push
  # push:
  #   paths:
  #     - 'obd/**'

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./obd
      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          python -m pytest
        working-directory: ./obd