name: Web Docker Image CI

on:
  push:
    # branches:
    #   - 'main'
    tags:
      - 'v*'

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup Node
        uses: actions/setup-node@v2
      - 
        name: Install Node Modules (client)
        run: npm install
        working-directory: ./web/client
      - 
        name: Build Client
        run: npm run build
        working-directory: ./web/client
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          flavor: latest=auto
          images: ${{ secrets.DOCKERHUB_USERNAME }}/onboardpi
          tags: type=semver,pattern={{version}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./web
          file: ./web/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm/v7
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/onboardpi:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/onboardpi:buildcache,mode=max